server:
  port: 7999


spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.99.219.43:3306/mybatis_study?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
