server:
  port: 7999

logging:
  level:
    com.libra.spring.demo: debug

spring:
  datasource:
    username: root
    password: xiaoxuan0401
    url: jdbc:mysql://127.0.0.1:3306/mybatis_study?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
#    backup:
#      username: root
#      password: xiaoxuan0401
#      jdbc-url: jdbc:mysql://127.0.0.1:3306/mybatis_study_backup?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
#      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

